# Generated by Django 5.2.1 on 2025-06-08 05:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bloguser_options_remove_bloguser_created_time_and_more'),
        ('blog', '0010_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthExg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, max_length=64)),
                ('realname', models.CharField(blank=True, max_length=64, null=True)),
                ('nickname', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.CharField(blank=True, max_length=16, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('province', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('figureurl', models.CharField(blank=True, max_length=256, null=True)),
                ('is_bind_user', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oauth Login Info',
                'verbose_name_plural': 'Oauth Login Info',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ReadingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reading Record',
                'verbose_name_plural': 'Reading Record',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='RedemptionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Redemption Code')),
                ('membership_type', models.CharField(choices=[('month', 'Monthly Membership'), ('quarter', 'Quarterly Membership'), ('lifetime', 'Lifetime Membership')], max_length=20, verbose_name='Membership Type')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('used_time', models.DateTimeField(blank=True, null=True, verbose_name='Used Time')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Time')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Used By')),
            ],
            options={
                'verbose_name': 'Redemption Code',
                'verbose_name_plural': 'Redemption Codes',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('month', 'Monthly Membership'), ('quarter', 'Quarterly Membership'), ('lifetime', 'Lifetime Membership')], default='month', max_length=20, verbose_name='Membership Type')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Membership',
                'verbose_name_plural': 'User Memberships',
                'ordering': ['-created_time'],
            },
        ),
    ]
