# Generated by Django 5.2.1 on 2025-05-25 16:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogsettings_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('last_modify_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modify time')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='video file')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='upload time')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'video',
                'ordering': ['-upload_time'],
            },
        ),
    ]
