# Generated by Django 5.2.1 on 2025-05-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='videos',
            field=models.ManyToManyField(blank=True, to='blog.video', verbose_name='related videos'),
        ),
    ]
