# Generated by Django 5.2.1 on 2025-06-14 12:22

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_images',
            field=jsonfield.fields.JSONField(blank=True, default=list, null=True, verbose_name='cover images'),
        ),
    ]
