# Generated by Django 5.2.1 on 2025-06-14 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_article_cover_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cover_images',
        ),
        migrations.AddField(
            model_name='article',
            name='show_images_in_list',
            field=models.BooleanField(default=True, verbose_name='show images in list'),
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1024, verbose_name='image URL')),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.article')),
            ],
            options={
                'verbose_name': 'Article Image',
                'verbose_name_plural': 'Article Images',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='selected_images_for_list',
            field=models.ManyToManyField(blank=True, related_name='article_list_images', to='blog.articleimage', verbose_name='selected images for list'),
        ),
    ]
