# Generated by Django 5.2.1 on 2025-06-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_articleimage_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='selected_images_for_list',
        ),
        migrations.RemoveField(
            model_name='article',
            name='show_images_in_list',
        ),
        migrations.AddField(
            model_name='article',
            name='banner_images',
            field=models.JSONField(blank=True, default=list, verbose_name='banner images'),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
