# Generated by Django 5.2.1 on 2025-06-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_article_selected_images_for_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='banner_images',
        ),
    ]
